# Generated by Django 2.2.5 on 2021-06-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210607_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(error_messages={'unique': 'A user with that nickname already exists.'}, max_length=30, unique=True),
        ),
    ]
