# Generated by Django 2.2.5 on 2021-06-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210624_2105'),
        ('users', '0006_auto_20210625_1521'),
    ]

    operations = [
    ]
