# Generated by Django 2.2.5 on 2021-07-02 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_studio_studio_best_photo'),
        ('users', '0008_merge_20210628_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_studio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studios', to='studios.Studio'),
        ),
    ]
