# Generated by Django 2.2.5 on 2021-07-25 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210723_2339'),
        ('users', '0013_auto_20210722_1515'),
        ('users', '0012_auto_20210725_0938'),
    ]

    operations = [
    ]
