# Generated by Django 3.1 on 2021-04-15 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studios', '0001_initial'),
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studios.studio'),
        ),
        migrations.AddField(
            model_name='concept',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='studios.studio'),
        ),
    ]
