# Generated by Django 2.2.5 on 2021-06-07 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
        ('concepts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='studio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='studios.Studio'),
        ),
        migrations.AddField(
            model_name='photo',
            name='studio',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studios.Studio'),
        ),
    ]
