# Generated by Django 3.1 on 2021-04-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20210415_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='concept_photos'),
        ),
    ]
