# Generated by Django 2.2.5 on 2021-06-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0002_auto_20210607_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='concept',
            name='service_config',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='concept',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='studios.Studio'),
        ),
    ]
