# Generated by Django 2.2.5 on 2021-06-07 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0003_auto_20210607_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='studio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studios.Studio'),
        ),
    ]
