# Generated by Django 2.2.5 on 2021-07-02 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0004_auto_20210607_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='concept',
            name='service_config',
            field=models.TextField(default=''),
        ),
    ]
