# Generated by Django 2.2.5 on 2021-07-04 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0005_auto_20210702_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='studio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studios.Studio'),
        ),
    ]
