# Generated by Django 2.2.5 on 2021-07-04 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0006_auto_20210704_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='studio',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='studios.Studio'),
        ),
    ]
