# Generated by Django 2.2.5 on 2021-07-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0007_auto_20210704_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_description',
            field=models.TextField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='concept',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
