# Generated by Django 2.2.5 on 2021-07-06 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0008_auto_20210706_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_description',
            field=models.TextField(default='', max_length=135),
        ),
    ]
