# Generated by Django 2.2.5 on 2021-07-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0011_auto_20210706_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
