# Generated by Django 2.2.5 on 2021-07-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0012_auto_20210706_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_description',
            field=models.TextField(default='', max_length=170),
        ),
    ]
