# Generated by Django 2.2.5 on 2021-07-26 05:36

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0016_auto_20210726_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, size=[512, 512], upload_to='concept_photos'),
        ),
    ]
