# Generated by Django 2.2.5 on 2021-07-26 05:41

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0017_auto_20210726_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, size=[512, 512], upload_to='concept_photos'),
        ),
    ]
