# Generated by Django 2.2.5 on 2021-09-20 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0019_auto_20210920_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='random_int',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
    ]
