# Generated by Django 2.2.5 on 2021-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concepts', '0022_photo_button_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='concept_description',
            field=models.TextField(blank=True, default='', max_length=160),
        ),
    ]
