# Generated by Django 2.2.5 on 2021-10-09 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms
import salons.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Concept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15)),
                ('concept_description', models.TextField(blank=True, default='', max_length=160)),
                ('service_config', models.TextField(default='')),
                ('price', models.TextField(blank=True, default='', max_length=160)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SalonBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Salon Badge',
            },
        ),
        migrations.CreateModel(
            name='Salon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=13)),
                ('kakao_chat', models.CharField(blank=True, max_length=140)),
                ('address', models.CharField(max_length=140)),
                ('addr_detail', models.CharField(blank=True, max_length=140)),
                ('addr_short', models.CharField(blank=True, max_length=140)),
                ('location', models.CharField(blank=True, max_length=140)),
                ('location_dong', models.CharField(blank=True, max_length=140)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('introduction', models.TextField(blank=True, default='')),
                ('using_info', models.TextField(blank=True, default='')),
                ('salon_avatar', django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='JPEG', keep_meta=True, null=True, quality=95, size=[1024, 1024], upload_to='salon_photos')),
                ('salon_lat', models.FloatField(blank=True)),
                ('salon_lng', models.FloatField(blank=True)),
                ('likes_user', models.ManyToManyField(blank=True, related_name='salon_likes_user', to=settings.AUTH_USER_MODEL)),
                ('salon_badge', models.ManyToManyField(blank=True, related_name='salons', to='salons.SalonBadge')),
                ('stylist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(blank=True, default='', max_length=80)),
                ('button_filter', models.CharField(blank=True, default='', max_length=80)),
                ('file', django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=95, size=[1024, 1024], upload_to='concept_photos')),
                ('random_int', models.CharField(blank=True, default=salons.models.Photo.random_string, max_length=6)),
                ('concept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='salons.Concept')),
                ('salon', models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='salons.Salon')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='concept',
            name='salon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concepts', to='salons.Salon'),
        ),
    ]
