# Generated by Django 2.2.5 on 2021-10-11 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concept',
            name='price',
        ),
    ]
