# Generated by Django 2.2.5 on 2021-10-11 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0002_remove_concept_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='concept',
            name='price',
            field=models.TextField(blank=True, default='', max_length=160),
        ),
    ]
