# Generated by Django 2.2.5 on 2021-10-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salons', '0004_auto_20211011_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concept',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=6),
        ),
    ]
