# Generated by Django 2.2.5 on 2021-05-02 07:32

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Studio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('en_name', models.CharField(default='', max_length=50)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None)),
                ('kakao_chat', models.CharField(blank=True, max_length=140)),
                ('city', models.CharField(max_length=80)),
                ('address', models.CharField(max_length=140)),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('bio', models.TextField(blank=True, default='')),
                ('file', models.ImageField(default='', upload_to='studio_photos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
