# Generated by Django 2.2.5 on 2021-06-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='bio',
            new_name='studio_introduction',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='name',
            new_name='studio_name',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='city',
        ),
        migrations.RemoveField(
            model_name='studio',
            name='en_name',
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_using_info',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
