# Generated by Django 3.1 on 2021-04-16 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_studio_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='kakao_chat',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
