# Generated by Django 2.2.5 on 2021-06-07 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0003_auto_20210607_2246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='studio_introduction',
            new_name='introduction',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='studio_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='studio_using_info',
            new_name='using_info',
        ),
    ]
