# Generated by Django 3.1 on 2021-04-18 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_studio_kakao_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='file',
            field=models.ImageField(default='', upload_to='studio_photos'),
        ),
    ]
