# Generated by Django 2.2.5 on 2021-06-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0004_auto_20210607_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='studio_photos'),
        ),
    ]
