# Generated by Django 3.1 on 2021-05-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_studio_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='en_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
