# Generated by Django 2.2.5 on 2021-06-24 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0005_auto_20210607_2253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='file',
            new_name='studio_avatar',
        ),
    ]
