# Generated by Django 2.2.5 on 2021-06-25 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0006_studio_likes_user'),
        ('studios', '0006_auto_20210624_2105'),
    ]

    operations = [
    ]
