# Generated by Django 2.2.5 on 2021-06-28 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0007_merge_20210625_1922'),
        ('studios', '0007_merge_20210625_1951'),
    ]

    operations = [
    ]
