# Generated by Django 2.2.5 on 2021-06-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0008_merge_20210628_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='studio_best_photo',
            field=models.ImageField(default='', upload_to='studio_photos'),
        ),
    ]
