# Generated by Django 2.2.5 on 2021-07-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0009_studio_studio_best_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='studio_lat',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_lng',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
