# Generated by Django 2.2.5 on 2021-07-08 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0010_auto_20210707_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='studio_best_photo',
            field=models.ImageField(blank=True, default='', upload_to='studio_photos'),
        ),
    ]
