# Generated by Django 2.2.5 on 2021-07-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0011_auto_20210708_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='studio_avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='studio_photos'),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_best_photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='studio_photos'),
        ),
    ]
