# Generated by Django 2.2.5 on 2021-07-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0012_auto_20210708_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
