# Generated by Django 2.2.5 on 2021-07-14 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0016_studio_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studio',
            old_name='addr',
            new_name='addr_detail',
        ),
        migrations.RenameField(
            model_name='studio',
            old_name='detail',
            new_name='addr_short',
        ),
    ]
