# Generated by Django 2.2.5 on 2021-07-15 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0017_auto_20210714_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='studio_lat',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='studio',
            name='studio_lng',
            field=models.FloatField(blank=True),
        ),
    ]
