# Generated by Django 2.2.5 on 2021-07-20 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0018_auto_20210715_1245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studio',
            name='studio_best_photo',
        ),
    ]
