# Generated by Django 2.2.5 on 2021-07-25 00:38

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0019_remove_studio_studio_best_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studio',
            name='studio_avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='', null=True, upload_to='studio_photos'),
        ),
    ]
