# Generated by Django 2.2.5 on 2021-09-07 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0022_auto_20210728_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudioBadge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Studio Badge',
            },
        ),
        migrations.AlterField(
            model_name='studio',
            name='phone_number',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AddField(
            model_name='studio',
            name='studio_badge',
            field=models.ManyToManyField(blank=True, related_name='studios', to='studios.StudioBadge'),
        ),
    ]
