# Generated by Django 2.2.5 on 2021-09-20 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studios', '0024_studio_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='studio',
            name='location_dong',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
